name: deploy

on:
  push:
  workflow_dispatch:
  # schedule:
  # Runs everyday at 8:00 AM
  # - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.TOKEN }}
          repository: 014-code.github.io/014.github.io
          branch: main
          folder: ./
          clean: false
          commit-message: ${{ github.event.head_commit.message }}